version: '3.10'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: python3 manage.py runserver 0.0.0.0:8000